// <auto-generated />
using System;
using CapitalPos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CapitalPos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CapitalPosDbContext))]
    [Migration("20260720223708_AgregarCategoriasYMarcas")]
    partial class AgregarCategoriasYMarcas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CapitalPos.Domain.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoriaPadreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("CategoriaPadreId", "EmpresaId");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreRazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "TipoDocumento", "NumeroDocumento")
                        .IsUnique()
                        .HasFilter("\"NumeroDocumento\" <> ''");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Comprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Correlativo")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoCpe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCdr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreXml")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NombreZip")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("VentaId", "EmpresaId");

                    b.HasIndex("EmpresaId", "TipoComprobante", "Serie", "Correlativo")
                        .IsUnique();

                    b.ToTable("comprobantes", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.ConfiguracionFiscalEmpresa", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Ubigeo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("EmpresaId");

                    b.HasIndex("EmpresaId")
                        .IsUnique();

                    b.ToTable("configuraciones_fiscales_empresas", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("Ruc")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("Costo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MarcaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("CategoriaId", "EmpresaId");

                    b.HasIndex("EmpresaId", "CodigoBarras")
                        .IsUnique()
                        .HasFilter("\"CodigoBarras\" <> ''");

                    b.HasIndex("EmpresaId", "CodigoSku")
                        .IsUnique()
                        .HasFilter("\"CodigoSku\" <> ''");

                    b.HasIndex("MarcaId", "EmpresaId");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.ProductoVariante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "CodigoBarras")
                        .IsUnique()
                        .HasFilter("\"CodigoBarras\" <> ''");

                    b.HasIndex("EmpresaId", "CodigoSku")
                        .IsUnique()
                        .HasFilter("\"CodigoSku\" <> ''");

                    b.HasIndex("EmpresaId", "ProductoId");

                    b.HasIndex("ProductoId", "EmpresaId");

                    b.ToTable("productos_variantes", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.PuntoVenta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "SedeId");

                    b.HasIndex("SedeId", "EmpresaId");

                    b.ToTable("puntos_venta", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Sede", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoEstablecimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "Nombre");

                    b.ToTable("sedes", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.SerieComprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("CorrelativoActual")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "SedeId");

                    b.HasIndex("SedeId", "EmpresaId");

                    b.HasIndex("EmpresaId", "SedeId", "TipoComprobante", "Serie")
                        .IsUnique();

                    b.ToTable("series_comprobante", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.StockProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("CantidadReservada")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductoVarianteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "SedeId");

                    b.HasIndex("ProductoId", "EmpresaId");

                    b.HasIndex("ProductoVarianteId", "EmpresaId");

                    b.HasIndex("SedeId", "EmpresaId");

                    b.HasIndex("EmpresaId", "SedeId", "ProductoId")
                        .IsUnique()
                        .HasFilter("\"ProductoVarianteId\" IS NULL");

                    b.HasIndex("EmpresaId", "SedeId", "ProductoVarianteId")
                        .IsUnique()
                        .HasFilter("\"ProductoVarianteId\" IS NOT NULL");

                    b.ToTable("stocks_productos", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.UsuarioCredencial", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Algoritmo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Activo", "Bloqueado");

                    b.ToTable("usuarios_credenciales", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.UsuarioEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UsuarioId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("usuarios_empresas", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CanalVenta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Igv")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PuntoVentaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("VendedorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ClienteId", "EmpresaId");

                    b.HasIndex("EmpresaId", "SedeId");

                    b.HasIndex("PuntoVentaId", "EmpresaId");

                    b.HasIndex("SedeId", "EmpresaId");

                    b.HasIndex("EmpresaId", "CanalVenta", "Fecha");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.VentaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Igv")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductoVarianteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EmpresaId", "VentaId");

                    b.HasIndex("ProductoId", "EmpresaId");

                    b.HasIndex("ProductoVarianteId", "EmpresaId");

                    b.HasIndex("VentaId", "EmpresaId");

                    b.ToTable("ventas_detalles", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Domain.Categoria", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaPadreId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CapitalPos.Domain.Cliente", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.Comprobante", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Venta", null)
                        .WithMany()
                        .HasForeignKey("VentaId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.ConfiguracionFiscalEmpresa", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithOne()
                        .HasForeignKey("CapitalPos.Domain.ConfiguracionFiscalEmpresa", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.Marca", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.Producto", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CapitalPos.Domain.Marca", null)
                        .WithMany()
                        .HasForeignKey("MarcaId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CapitalPos.Domain.ProductoVariante", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.PuntoVenta", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Sede", null)
                        .WithMany()
                        .HasForeignKey("SedeId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.Sede", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.SerieComprobante", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Sede", null)
                        .WithMany()
                        .HasForeignKey("SedeId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.StockProducto", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.ProductoVariante", null)
                        .WithMany()
                        .HasForeignKey("ProductoVarianteId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CapitalPos.Domain.Sede", null)
                        .WithMany()
                        .HasForeignKey("SedeId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.UsuarioCredencial", b =>
                {
                    b.HasOne("CapitalPos.Domain.Usuario", null)
                        .WithOne()
                        .HasForeignKey("CapitalPos.Domain.UsuarioCredencial", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.UsuarioEmpresa", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.Venta", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CapitalPos.Domain.PuntoVenta", null)
                        .WithMany()
                        .HasForeignKey("PuntoVentaId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Sede", null)
                        .WithMany()
                        .HasForeignKey("SedeId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.VentaDetalle", b =>
                {
                    b.HasOne("CapitalPos.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Domain.ProductoVariante", null)
                        .WithMany()
                        .HasForeignKey("ProductoVarianteId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CapitalPos.Domain.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Domain.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
